import { Exercise } from '../types/workout';

export const SEED_EXERCISES: Omit<Exercise, 'isCustom'>[] = [
  // ==========================================
  // PEITORAL (CHEST)
  // ==========================================
  {
    id: 'barbell_bench_press',
    name: 'Supino Reto com Barra',
    nameEn: 'Barbell Flat Bench Press',
    targetMuscle: 'peito',
    synergistMuscles: ['triceps', 'ombros'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Deite no banco, pés firmes no chão, faça a retração escapular. Desça a barra controladamente até o terço inferior do esterno e empurre com força.',
  },
  {
    id: 'incline_barbell_bench_press',
    name: 'Supino Inclinado com Barra',
    nameEn: 'Barbell Incline Bench Press',
    targetMuscle: 'peito',
    synergistMuscles: ['ombros', 'triceps'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Banco entre 30º e 45º. Foco maior na porção clavicular (superior) do peitoral.',
  },
  {
    id: 'decline_barbell_bench_press',
    name: 'Supino Declinado com Barra',
    nameEn: 'Barbell Decline Bench Press',
    targetMuscle: 'peito',
    synergistMuscles: ['triceps', 'ombros'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Banco declinado a 15-30º. Ênfase na porção inferior (costal) do peitoral maior.',
  },
  {
    id: 'dumbbell_bench_press',
    name: 'Supino Reto com Halteres',
    nameEn: 'Flat Dumbbell Bench Press',
    targetMuscle: 'peito',
    synergistMuscles: ['triceps', 'ombros'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Permite maior arco de adução e liberdade de rotação articular para os ombros.',
  },
  {
    id: 'incline_dumbbell_bench_press',
    name: 'Supino Inclinado com Halteres',
    nameEn: 'Incline Dumbbell Bench Press',
    targetMuscle: 'peito',
    synergistMuscles: ['ombros', 'triceps'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Incline o banco a 30º. Desça os halteres alongando o feixe superior do peitoral.',
  },
  {
    id: 'decline_dumbbell_bench_press',
    name: 'Supino Declinado com Halteres',
    nameEn: 'Decline Dumbbell Bench Press',
    targetMuscle: 'peito',
    synergistMuscles: ['triceps', 'ombros'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Permite maior amplitude na porção inferior do peitoral sem restringir o punho.',
  },
  {
    id: 'machine_chest_press',
    name: 'Supino Máquina Sentado',
    nameEn: 'Seated Machine Chest Press',
    targetMuscle: 'peito',
    synergistMuscles: ['triceps', 'ombros'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'machine',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 90,
    instructions: 'Ajuste a altura do banco para que as manoplas fiquem na linha dos mamilos.',
  },
  {
    id: 'incline_machine_chest_press',
    name: 'Supino Inclinado Máquina Articulada',
    nameEn: 'Incline Machine Chest Press',
    targetMuscle: 'peito',
    synergistMuscles: ['ombros', 'triceps'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Foco na parte superior com curva de resistência progressiva estável.',
  },
  {
    id: 'smith_bench_press',
    name: 'Supino Reto no Smith',
    nameEn: 'Smith Machine Flat Bench Press',
    targetMuscle: 'peito',
    synergistMuscles: ['triceps', 'ombros'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'smith',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Barra guiada que permite sobrecarga máxima com menor demanda estabilizadora.',
  },
  {
    id: 'smith_incline_bench_press',
    name: 'Supino Inclinado no Smith',
    nameEn: 'Smith Machine Incline Bench Press',
    targetMuscle: 'peito',
    synergistMuscles: ['ombros', 'triceps'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'smith',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Posicione o banco a 30-45º diretamente abaixo da trajetória guiada da barra.',
  },
  {
    id: 'flat_dumbbell_fly',
    name: 'Crucifixo Reto com Halteres',
    nameEn: 'Flat Dumbbell Fly',
    targetMuscle: 'peito',
    synergistMuscles: ['ombros'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 60,
    instructions: 'Cotovelos levemente flexionados durante todo o movimento para evitar estresse articular.',
  },
  {
    id: 'incline_dumbbell_fly',
    name: 'Crucifixo Inclinado com Halteres',
    nameEn: 'Incline Dumbbell Fly',
    targetMuscle: 'peito',
    synergistMuscles: ['ombros'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 60,
    instructions: 'Alongamento sob carga focado nas fibras superiores do peitoral maior.',
  },
  {
    id: 'pec_deck_fly',
    name: 'Crucifixo na Máquina (Peck Deck / Voador)',
    nameEn: 'Pec Deck Machine Fly',
    targetMuscle: 'peito',
    synergistMuscles: ['ombros'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'machine',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 60,
    instructions: 'Mantenha os cotovelos na altura do peitoral médio e aperte no pico de contração.',
  },
  {
    id: 'cable_crossover_high_to_low',
    name: 'Crossover Polia Alta (Descendente)',
    nameEn: 'High to Low Cable Fly',
    targetMuscle: 'peito',
    synergistMuscles: ['ombros'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'multiplanar',
    defaultRestSeconds: 60,
    instructions: 'Cabos posicionados no topo. Puxe para baixo e para frente cruzando as mãos levemente.',
  },
  {
    id: 'cable_crossover_middle',
    name: 'Crossover Polia Média',
    nameEn: 'Mid-Cable Crossover',
    targetMuscle: 'peito',
    synergistMuscles: ['ombros'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 60,
    instructions: 'Polias na altura do tórax. Movimento clássico de adução horizontal pura.',
  },
  {
    id: 'cable_crossover_low_to_high',
    name: 'Crossover Polia Baixa (Ascendente)',
    nameEn: 'Low to High Cable Fly',
    targetMuscle: 'peito',
    synergistMuscles: ['ombros'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'multiplanar',
    defaultRestSeconds: 60,
    instructions: 'Polias no chão. Traga as manoplas para cima e para frente até a altura do queixo.',
  },
  {
    id: 'pushup_standard',
    name: 'Flexão de Braço no Solo',
    nameEn: 'Standard Push-Up',
    targetMuscle: 'peito',
    synergistMuscles: ['triceps', 'ombros', 'abdomen'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Corpo em linha reta, glúteos e abdômen travados. Desça o peito até tocar o chão.',
  },
  {
    id: 'weighted_pushup',
    name: 'Flexão de Braço com Sobrecarga',
    nameEn: 'Weighted Push-Up',
    targetMuscle: 'peito',
    synergistMuscles: ['triceps', 'ombros', 'abdomen'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Anilha posicionada sobre a coluna torácica superior.',
  },
  {
    id: 'chest_dips',
    name: 'Mergulho nas Paralelas (Foco Peitoral)',
    nameEn: 'Chest Dips',
    targetMuscle: 'peito',
    synergistMuscles: ['triceps', 'ombros'],
    movementPattern: 'vertical_push',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Incline o tronco para frente a cerca de 30º e abra levemente os cotovelos.',
  },
  {
    id: 'dumbbell_pullover',
    name: 'Pullover com Halter',
    nameEn: 'Dumbbell Pullover',
    targetMuscle: 'peito',
    synergistMuscles: ['costas', 'triceps'],
    movementPattern: 'isolation',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Apoiado transversalmente no banco. Alongue os braços acima da cabeça mantendo os quadris baixos.',
  },
  {
    id: 'floor_press_barbell',
    name: 'Floor Press com Barra (Supino no Solo)',
    nameEn: 'Barbell Floor Press',
    targetMuscle: 'peito',
    synergistMuscles: ['triceps', 'ombros'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Excelente para sobrecarga de tríceps e peito sem risco de hiperestiramento de ombro.',
  },

  // ==========================================
  // COSTAS & DORSAL (BACK)
  // ==========================================
  {
    id: 'deadlift_conventional',
    name: 'Levantamento Terra Convencional',
    nameEn: 'Conventional Deadlift',
    targetMuscle: 'costas',
    synergistMuscles: ['isquiotibiais', 'gluteos', 'quadriceps', 'trapezio', 'antibraco'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 180,
    instructions: 'Pés na largura do quadril, coluna neutra, tracione a barra rente às canelas.',
  },
  {
    id: 'deadlift_sumo',
    name: 'Levantamento Terra Sumô',
    nameEn: 'Sumo Deadlift',
    targetMuscle: 'costas',
    synergistMuscles: ['gluteos', 'quadriceps', 'isquiotibiais', 'trapezio'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 180,
    instructions: 'Base aberta com pontas dos pés a 45º. Menor braço de momento lombar e maior ativação de quadril.',
  },
  {
    id: 'pull_up_pronated',
    name: 'Barra Fixa Pronada (Pull-Up)',
    nameEn: 'Overhand Pull-Up',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'ombros', 'trapezio'],
    movementPattern: 'vertical_pull',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 120,
    instructions: 'Pegada além da largura dos ombros. Puxe o peito em direção à barra até que o queixo passe dela.',
  },
  {
    id: 'chin_up_supinated',
    name: 'Barra Fixa Supinada (Chin-Up)',
    nameEn: 'Underhand Chin-Up',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps'],
    movementPattern: 'vertical_pull',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Palmas voltadas para você. Excelente ativação conjunta do grande dorsal e do bíceps.',
  },
  {
    id: 'pull_up_neutral',
    name: 'Barra Fixa Pegada Neutra',
    nameEn: 'Neutral Grip Pull-Up',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'antibraco'],
    movementPattern: 'vertical_pull',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Palmas voltadas uma para a outra. Mais amigável para a articulação dos ombros.',
  },
  {
    id: 'lat_pulldown_wide',
    name: 'Puxada Alta com Barra (Pegada Aberta)',
    nameEn: 'Wide-Grip Lat Pulldown',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'ombros'],
    movementPattern: 'vertical_pull',
    mechanic: 'compound',
    equipment: 'cable',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 90,
    instructions: 'Puxe a barra até a altura da clavícula, estufando o peitoral e estabilizando as escápulas.',
  },
  {
    id: 'lat_pulldown_close_grip',
    name: 'Puxada Alta com Triângulo (Pegada Fechada)',
    nameEn: 'Close Grip Lat Pulldown',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'ombros'],
    movementPattern: 'vertical_pull',
    mechanic: 'compound',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Foco no alongamento profundo do grande dorsal no topo do movimento.',
  },
  {
    id: 'lat_pulldown_underhand',
    name: 'Puxada Alta Supinada',
    nameEn: 'Reverse Grip Lat Pulldown',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps'],
    movementPattern: 'vertical_pull',
    mechanic: 'compound',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Pegada na largura dos ombros com palmas para cima, puxando até a base do esterno.',
  },
  {
    id: 'barbell_bent_over_row',
    name: 'Remada Curvada com Barra (Pegada Pronada)',
    nameEn: 'Barbell Bent Over Row',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'ombros', 'trapezio', 'lombar'],
    movementPattern: 'horizontal_pull',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Tronco inclinado a 45º, coluna neutra. Puxe a barra em direção ao umbigo.',
  },
  {
    id: 'yates_row_supinated',
    name: 'Remada Curvada Supinada (Yates Row)',
    nameEn: 'Reverse Grip Bent Over Row',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'ombros', 'trapezio'],
    movementPattern: 'horizontal_pull',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Tronco um pouco mais ereto (~60º), palmas para cima. Puxada direta no quadril.',
  },
  {
    id: 'pendlay_row',
    name: 'Remada Pendlay (Do Chão)',
    nameEn: 'Pendlay Row',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'trapezio', 'lombar'],
    movementPattern: 'horizontal_pull',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Tronco paralelo ao chão (90º). Cada repetição parte estática do solo com puxada explosiva.',
  },
  {
    id: 't_bar_row',
    name: 'Remada Cavalinho (T-Bar Row)',
    nameEn: 'T-Bar Row',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'trapezio', 'lombar'],
    movementPattern: 'horizontal_pull',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Excelente construtor de espessura e densidade para toda a musculatura das costas.',
  },
  {
    id: 'seated_cable_row',
    name: 'Remada Baixa na Polia com Triângulo',
    nameEn: 'Seated Cable Row',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'ombros', 'trapezio'],
    movementPattern: 'horizontal_pull',
    mechanic: 'compound',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Coluna ereta, ombros encaixados. Puxe o triângulo até o abdômen sem jogar a lombar.',
  },
  {
    id: 'seated_cable_row_wide',
    name: 'Remada Baixa com Barra Pegada Aberta',
    nameEn: 'Wide Grip Seated Cable Row',
    targetMuscle: 'costas',
    synergistMuscles: ['ombros', 'trapezio'],
    movementPattern: 'horizontal_pull',
    mechanic: 'compound',
    equipment: 'cable',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 90,
    instructions: 'Foco nos rombóides, trapézio médio e deltóide posterior.',
  },
  {
    id: 'dumbbell_single_arm_row',
    name: 'Remada Unilateral com Halter (Serrote)',
    nameEn: 'One-Arm Dumbbell Row',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'ombros'],
    movementPattern: 'horizontal_pull',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Um joelho e mão no banco. Puxe o halter em direção ao quadril, mantendo o tronco estável.',
  },
  {
    id: 'chest_supported_dumbbell_row',
    name: 'Remada no Banco Inclinado com Halteres',
    nameEn: 'Chest Supported Dumbbell Row',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'ombros', 'trapezio'],
    movementPattern: 'horizontal_pull',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Peito apoiado no banco inclinado a 30-45º. Elimina impulso lombar e foca 100% na dorsal.',
  },
  {
    id: 'straight_arm_pulldown_rope',
    name: 'Pulldown no Cabo com Corda',
    nameEn: 'Rope Straight Arm Pulldown',
    targetMuscle: 'costas',
    synergistMuscles: ['triceps'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Braços quase estendidos. Puxe a corda para baixo em semicírculo até as coxas.',
  },
  {
    id: 'straight_arm_pulldown_bar',
    name: 'Pulldown no Cabo com Barra',
    nameEn: 'Straight Arm Cable Pulldown',
    targetMuscle: 'costas',
    synergistMuscles: ['triceps'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Isolamento contínuo das fibras laterais do grande dorsal.',
  },
  {
    id: 'rack_pull',
    name: 'Rack Pull (Levantamento Terra Parcial)',
    nameEn: 'Barbell Rack Pull',
    targetMuscle: 'costas',
    synergistMuscles: ['trapezio', 'lombar', 'gluteos', 'antibraco'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 150,
    instructions: 'Barra apoiada nos pinos da gaiola logo abaixo dos joelhos. Sobrecarga máxima de espessura.',
  },
  {
    id: 'hyperextension_45',
    name: 'Hiperextensão Lombar no Banco 45º',
    nameEn: '45-Degree Hyperextension',
    targetMuscle: 'lombar',
    synergistMuscles: ['gluteos', 'isquiotibiais'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Dobre pelo quadril e erga o tronco até alinhar com as pernas, sem hiperestender a coluna.',
  },

  // ==========================================
  // QUADRÍCEPS (QUADS)
  // ==========================================
  {
    id: 'barbell_back_squat_high_bar',
    name: 'Agachamento Livre Barra Alta (High Bar)',
    nameEn: 'Barbell High Bar Back Squat',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos', 'isquiotibiais', 'abdomen', 'lombar'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 180,
    instructions: 'Barra sobre o trapézio superior. Tronco mais ereto, joelhos viajam para frente com profundidade.',
  },
  {
    id: 'barbell_back_squat_low_bar',
    name: 'Agachamento Livre Barra Baixa (Low Bar)',
    nameEn: 'Barbell Low Bar Back Squat',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos', 'isquiotibiais', 'lombar'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 180,
    instructions: 'Barra sobre a espinha da escápula. Maior flexão de quadril e sobrecarga de cadeia posterior.',
  },
  {
    id: 'barbell_front_squat',
    name: 'Agachamento Frontal com Barra (Front Squat)',
    nameEn: 'Barbell Front Squat',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos', 'abdomen', 'lombar'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 150,
    instructions: 'Barra apoiada nos deltóides anteriores. Tronco 100% vertical, exigindo máxima força de quadríceps e core.',
  },
  {
    id: 'zercher_squat',
    name: 'Agachamento Zercher',
    nameEn: 'Zercher Squat',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos', 'abdomen', 'trapezio', 'biceps'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 150,
    instructions: 'Barra apoiada na dobra dos cotovelos. Fortalecimento bruto do core e pernas.',
  },
  {
    id: 'leg_press_45_degree',
    name: 'Leg Press 45º',
    nameEn: '45-Degree Leg Press',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos', 'isquiotibiais'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Pés na largura dos ombros no meio da plataforma. Não tire a lombar do encosto.',
  },
  {
    id: 'hack_squat_machine',
    name: 'Hack Squat na Máquina',
    nameEn: 'Machine Hack Squat',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Costas firmes no apoio. Permite flexão profunda do joelho com isolamento maciço de vastos.',
  },
  {
    id: 'smith_machine_squat',
    name: 'Agachamento no Smith',
    nameEn: 'Smith Machine Squat',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'smith',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Pés posicionados um pouco à frente da barra para focar na extensão do joelho.',
  },
  {
    id: 'leg_extension_machine',
    name: 'Cadeira Extensora',
    nameEn: 'Leg Extension Machine',
    targetMuscle: 'quadriceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Estenda os joelhos completamente, segure 1 segundo no pico e desça controladamente.',
  },
  {
    id: 'single_leg_extension',
    name: 'Cadeira Extensora Unilateral',
    nameEn: 'Single-Leg Extension',
    targetMuscle: 'quadriceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Excelente para correção de assimetrias de força entre os membros inferiores.',
  },
  {
    id: 'bulgarian_split_squat_dumbbells',
    name: 'Agachamento Búlgaro com Halteres',
    nameEn: 'Dumbbell Bulgarian Split Squat',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos', 'isquiotibiais'],
    movementPattern: 'lunge',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Peito do pé de trás apoiado no banco. Desça verticalmente até a coxa da frente ficar paralela ao chão.',
  },
  {
    id: 'bulgarian_split_squat_smith',
    name: 'Agachamento Búlgaro no Smith',
    nameEn: 'Smith Machine Bulgarian Split Squat',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos', 'isquiotibiais'],
    movementPattern: 'lunge',
    mechanic: 'compound',
    equipment: 'smith',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Maior estabilidade que permite carga progressiva elevada por perna.',
  },
  {
    id: 'walking_lunge_dumbbells',
    name: 'Passada / Avanço com Halteres',
    nameEn: 'Walking Dumbbell Lunge',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos', 'isquiotibiais', 'panturrilhas'],
    movementPattern: 'lunge',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Dê passos firmes e controlados sem deixar o joelho colapsar para dentro.',
  },
  {
    id: 'goblet_squat_dumbbell',
    name: 'Goblet Squat com Halter',
    nameEn: 'Goblet Squat',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos', 'abdomen'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 75,
    instructions: 'Segure o halter verticalmente junto ao peito com ambas as mãos.',
  },
  {
    id: 'sissy_squat',
    name: 'Sissy Squat',
    nameEn: 'Sissy Squat',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['abdomen'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Isolamento extremo do reto femoral sob alongamento articular máximo.',
  },
  {
    id: 'step_up_box',
    name: 'Step Up na Caixa com Halteres',
    nameEn: 'Dumbbell Step-Up',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos'],
    movementPattern: 'lunge',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 75,
    instructions: 'Suba na caixa empurrando apenas com a perna de cima sem pegar impulso com o pé de trás.',
  },

  // ==========================================
  // ISQUIOTIBIAIS & POSTERIORES (HAMSTRINGS)
  // ==========================================
  {
    id: 'romanian_deadlift_barbell',
    name: 'Levantamento Terra Romeno (RDL com Barra)',
    nameEn: 'Barbell Romanian Deadlift (RDL)',
    targetMuscle: 'isquiotibiais',
    synergistMuscles: ['gluteos', 'lombar', 'antibraco'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Joelhos com leve microflexão fixa. Projete o quadril para trás até sentir o alongamento máximo dos posteriores.',
  },
  {
    id: 'romanian_deadlift_dumbbell',
    name: 'RDL com Halteres',
    nameEn: 'Dumbbell Romanian Deadlift',
    targetMuscle: 'isquiotibiais',
    synergistMuscles: ['gluteos', 'lombar'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Mantenha os halteres colados às coxas e canelas durante toda a descida.',
  },
  {
    id: 'stiff_leg_deadlift_barbell',
    name: 'Stiff com Barra',
    nameEn: 'Barbell Stiff-Leg Deadlift',
    targetMuscle: 'isquiotibiais',
    synergistMuscles: ['gluteos', 'lombar'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Pernas mais retas e quadril alto, exigindo flexibilidade e força isométrica dos posteriores.',
  },
  {
    id: 'lying_leg_curl_machine',
    name: 'Mesa Flexora Deitada',
    nameEn: 'Lying Leg Curl Machine',
    targetMuscle: 'isquiotibiais',
    synergistMuscles: ['panturrilhas'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Mantenha o quadril colado no estofado. Flexione os joelhos levando os calcanhares aos glúteos.',
  },
  {
    id: 'seated_leg_curl_machine',
    name: 'Cadeira Flexora Sentada',
    nameEn: 'Seated Leg Curl Machine',
    targetMuscle: 'isquiotibiais',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Com o quadril flexionado a 90º, os isquiotibiais trabalham em posição de maior alongamento fisiológico.',
  },
  {
    id: 'standing_leg_curl_machine',
    name: 'Flexora em Pé Unilateral na Máquina',
    nameEn: 'Standing Single Leg Curl',
    targetMuscle: 'isquiotibiais',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Isolamento unilateral focado na cabeça curta do bíceps femoral.',
  },
  {
    id: 'nordic_hamstring_curl',
    name: 'Flexão Nórdica (Nordic Hamstring Curl)',
    nameEn: 'Nordic Hamstring Curl',
    targetMuscle: 'isquiotibiais',
    synergistMuscles: ['gluteos', 'panturrilhas'],
    movementPattern: 'isolation',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Tornozelos presos. Desça o tronco em linha reta controlando a fase excêntrica o máximo possível.',
  },
  {
    id: 'good_morning_barbell',
    name: 'Bom Dia (Good Morning) com Barra',
    nameEn: 'Barbell Good Morning',
    targetMuscle: 'isquiotibiais',
    synergistMuscles: ['gluteos', 'lombar'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Barra sobre o trapézio. Dobre o quadril para trás mantendo a coluna torácica firme e travada.',
  },

  // ==========================================
  // GLÚTEOS (GLUTES)
  // ==========================================
  {
    id: 'barbell_hip_thrust',
    name: 'Elevação Pélvica com Barra (Hip Thrust)',
    nameEn: 'Barbell Hip Thrust',
    targetMuscle: 'gluteos',
    synergistMuscles: ['isquiotibiais', 'quadriceps'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Costas apoiadas no banco na altura das escápulas. Empurre pelo calcanhar até estender totalmente o quadril.',
  },
  {
    id: 'smith_machine_hip_thrust',
    name: 'Elevação Pélvica no Smith',
    nameEn: 'Smith Machine Hip Thrust',
    targetMuscle: 'gluteos',
    synergistMuscles: ['isquiotibiais'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'smith',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Barra fixa guiada facilitando o posicionamento e controle de carga pesada.',
  },
  {
    id: 'cable_glute_kickback',
    name: 'Glúteo Coice no Cabo (Kickback)',
    nameEn: 'Cable Glute Kickback',
    targetMuscle: 'gluteos',
    synergistMuscles: ['isquiotibiais'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Tornozeleira presa no cabo baixo. Estenda a perna para trás contraindo o glúteo máximo.',
  },
  {
    id: 'seated_abductor_machine',
    name: 'Cadeira Abdutora na Máquina',
    nameEn: 'Seated Hip Abduction Machine',
    targetMuscle: 'gluteos',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'machine',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 60,
    instructions: 'Foco no glúteo médio e mínimo. Incline levemente o tronco para frente para maior ativação.',
  },
  {
    id: 'sumo_squat_dumbbell',
    name: 'Agachamento Sumô com Halter',
    nameEn: 'Dumbbell Sumo Squat',
    targetMuscle: 'gluteos',
    synergistMuscles: ['quadriceps', 'isquiotibiais'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 90,
    instructions: 'Base bem aberta com pontas voltadas para fora, descendo o halter entre as pernas.',
  },

  // ==========================================
  // OMBROS & DELTÓIDES (SHOULDERS)
  // ==========================================
  {
    id: 'overhead_press_barbell_standing',
    name: 'Desenvolvimento Militar em Pé com Barra (OHP)',
    nameEn: 'Standing Barbell Overhead Press',
    targetMuscle: 'ombros',
    synergistMuscles: ['triceps', 'trapezio', 'abdomen'],
    movementPattern: 'vertical_push',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 120,
    instructions: 'Pressione a barra verticalmente acima da cabeça travando glúteos e abdômen.',
  },
  {
    id: 'overhead_press_barbell_seated',
    name: 'Desenvolvimento com Barra Sentado',
    nameEn: 'Seated Barbell Overhead Press',
    targetMuscle: 'ombros',
    synergistMuscles: ['triceps', 'trapezio'],
    movementPattern: 'vertical_push',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 120,
    instructions: 'Banco a 90º. Elimina auxílio das pernas e isola o feixe anterior e medial do deltóide.',
  },
  {
    id: 'dumbbell_shoulder_press_seated',
    name: 'Desenvolvimento com Halteres Sentado',
    nameEn: 'Seated Dumbbell Shoulder Press',
    targetMuscle: 'ombros',
    synergistMuscles: ['triceps', 'trapezio'],
    movementPattern: 'vertical_push',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 90,
    instructions: 'Empurre os halteres para cima em arco convergente sem bater no topo.',
  },
  {
    id: 'arnold_press_dumbbell',
    name: 'Desenvolvimento Arnold com Halteres',
    nameEn: 'Arnold Dumbbell Press',
    targetMuscle: 'ombros',
    synergistMuscles: ['triceps', 'trapezio'],
    movementPattern: 'vertical_push',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'multiplanar',
    defaultRestSeconds: 90,
    instructions: 'Inicie com palmas viradas para você e rotacione para fora à medida que empurra para cima.',
  },
  {
    id: 'machine_shoulder_press',
    name: 'Desenvolvimento na Máquina Articulada',
    nameEn: 'Machine Shoulder Press',
    targetMuscle: 'ombros',
    synergistMuscles: ['triceps'],
    movementPattern: 'vertical_push',
    mechanic: 'compound',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Excelente para sobrecarga máxima e falha com segurança mecânica.',
  },
  {
    id: 'dumbbell_lateral_raise_standing',
    name: 'Elevação Lateral com Halteres em Pé',
    nameEn: 'Standing Dumbbell Lateral Raise',
    targetMuscle: 'ombros',
    synergistMuscles: ['trapezio'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 60,
    instructions: 'Eleve os braços no plano escapular (~30º à frente) até a altura dos ombros.',
  },
  {
    id: 'dumbbell_lateral_raise_seated',
    name: 'Elevação Lateral com Halteres Sentado',
    nameEn: 'Seated Dumbbell Lateral Raise',
    targetMuscle: 'ombros',
    synergistMuscles: ['trapezio'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 60,
    instructions: 'Elimina impulso das pernas e quadril para tensão estrita no deltóide lateral.',
  },
  {
    id: 'cable_lateral_raise_single_arm',
    name: 'Elevação Lateral no Cabo Unilateral',
    nameEn: 'Single-Arm Cable Lateral Raise',
    targetMuscle: 'ombros',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 60,
    instructions: 'Cabo posicionado na altura do joelho ou punho, mantendo tensão contínua em toda a amplitude.',
  },
  {
    id: 'cable_lateral_raise_behind_back',
    name: 'Elevação Lateral no Cabo Atrás do Tronco',
    nameEn: 'Behind-the-Back Cable Lateral Raise',
    targetMuscle: 'ombros',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 60,
    instructions: 'Cabo passando por trás do quadril para maior estiramento inicial das fibras.',
  },
  {
    id: 'machine_lateral_raise',
    name: 'Elevação Lateral na Máquina',
    nameEn: 'Machine Lateral Raise',
    targetMuscle: 'ombros',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'machine',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 60,
    instructions: 'Almofadas apoiadas nos braços, eliminando a fadiga de pegada dos antebraços.',
  },
  {
    id: 'cable_face_pull',
    name: 'Face Pull na Polia com Corda',
    nameEn: 'Rope Face Pull',
    targetMuscle: 'ombros',
    synergistMuscles: ['trapezio'],
    movementPattern: 'horizontal_pull',
    mechanic: 'compound',
    equipment: 'cable',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 60,
    instructions: 'Puxe a corda em direção aos olhos separando as mãos e rotacionando externamente os ombros.',
  },
  {
    id: 'reverse_pec_deck_fly',
    name: 'Crucifixo Inverso na Máquina (Peck Deck Invertido)',
    nameEn: 'Reverse Pec Deck Fly',
    targetMuscle: 'ombros',
    synergistMuscles: ['trapezio'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'machine',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 60,
    instructions: 'Ajuste os braços para a frente e empurre para trás focando no deltóide posterior.',
  },
  {
    id: 'bent_over_dumbbell_rear_delt_fly',
    name: 'Crucifixo Inverso com Halteres Curvado',
    nameEn: 'Bent-Over Dumbbell Rear Delt Fly',
    targetMuscle: 'ombros',
    synergistMuscles: ['trapezio'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 60,
    instructions: 'Tronco inclinado a 45-60º. Abra os braços lateralmente sem juntar excessivamente as escápulas.',
  },
  {
    id: 'dumbbell_front_raise',
    name: 'Elevação Frontal com Halteres',
    nameEn: 'Dumbbell Front Raise',
    targetMuscle: 'ombros',
    synergistMuscles: ['peito'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Eleve o halter até a linha dos olhos, focando na porção anterior do deltóide.',
  },

  // ==========================================
  // BÍCEPS & ANTEBRAÇO (BICEPS & FOREARMS)
  // ==========================================
  {
    id: 'barbell_curl_straight_bar',
    name: 'Rosca Direta com Barra Reta',
    nameEn: 'Standing Barbell Biceps Curl',
    targetMuscle: 'biceps',
    synergistMuscles: ['antibraco'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Cotovelos fixos ao lado do tronco. Flexione sem balançar o corpo.',
  },
  {
    id: 'ez_bar_curl',
    name: 'Rosca Direta com Barra W (EZ-Bar)',
    nameEn: 'EZ-Bar Biceps Curl',
    targetMuscle: 'biceps',
    synergistMuscles: ['antibraco'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Ângulo anatômico da pegada semi-supinada que protege os punhos.',
  },
  {
    id: 'dumbbell_bicep_curl_alternating',
    name: 'Rosca Alternada com Halteres em Pé',
    nameEn: 'Standing Alternating Dumbbell Curl',
    targetMuscle: 'biceps',
    synergistMuscles: ['antibraco'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Inicie com pegada neutra e faça supinação completa na subida.',
  },
  {
    id: 'incline_dumbbell_curl',
    name: 'Rosca no Banco Inclinado 45º com Halteres',
    nameEn: 'Incline Dumbbell Curl',
    targetMuscle: 'biceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 75,
    instructions: 'Coloca a cabeça longa do bíceps sob máximo estiramento passivo atrás do tronco.',
  },
  {
    id: 'hammer_curl_dumbbells',
    name: 'Rosca Martelo com Halteres',
    nameEn: 'Dumbbell Hammer Curl',
    targetMuscle: 'biceps',
    synergistMuscles: ['antibraco'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Palmas voltadas uma para a outra. Construtor chave do braquial e braquiorradial.',
  },
  {
    id: 'cable_rope_hammer_curl',
    name: 'Rosca Martelo na Polia com Corda',
    nameEn: 'Cable Rope Hammer Curl',
    targetMuscle: 'biceps',
    synergistMuscles: ['antibraco'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Tensão contínua proporcionada pelo cabo com pegada neutra.',
  },
  {
    id: 'preacher_curl_ez_bar',
    name: 'Rosca Scott com Barra W',
    nameEn: 'Preacher Curl with EZ-Bar',
    targetMuscle: 'biceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 75,
    instructions: 'Braços fixos na almofada inclinada, impedindo qualquer assistência do ombro.',
  },
  {
    id: 'preacher_curl_dumbbell',
    name: 'Rosca Scott Unilateral com Halter',
    nameEn: 'One-Arm Dumbbell Preacher Curl',
    targetMuscle: 'biceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Controle excêntrico preciso e eliminação de assimetrias.',
  },
  {
    id: 'concentration_curl_dumbbell',
    name: 'Rosca Concentrada com Halter',
    nameEn: 'Dumbbell Concentration Curl',
    targetMuscle: 'biceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Cotovelo apoiado na parte interna da coxa. Pico de contração máximo.',
  },
  {
    id: 'spider_curl_barbell',
    name: 'Rosca Spider com Barra W',
    nameEn: 'Spider Curl with EZ-Bar',
    targetMuscle: 'biceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Tronco deitado de bruços no banco inclinado, braços pendendo verticalmente.',
  },
  {
    id: 'cable_straight_bar_curl',
    name: 'Rosca Bíceps na Polia Baixa com Barra',
    nameEn: 'Cable Biceps Curl',
    targetMuscle: 'biceps',
    synergistMuscles: ['antibraco'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Resistência uniforme ao longo de toda a amplitude de flexão do cotovelo.',
  },
  {
    id: 'reverse_curl_ez_bar',
    name: 'Rosca Inversa com Barra W',
    nameEn: 'Reverse Grip EZ-Bar Curl',
    targetMuscle: 'antibraco',
    synergistMuscles: ['biceps'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Palmas voltadas para baixo. Foco maciço no braquiorradial e extensores de punho.',
  },
  {
    id: 'wrist_curl_barbell',
    name: 'Flexão de Punho com Barra (Antebraço)',
    nameEn: 'Barbell Wrist Curl',
    targetMuscle: 'antibraco',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 45,
    instructions: 'Antebraços apoiados no banco, flexionando os punhos para cima.',
  },

  // ==========================================
  // TRÍCEPS (TRICEPS)
  // ==========================================
  {
    id: 'parallel_bar_dips_triceps',
    name: 'Mergulho nas Paralelas (Foco Tríceps)',
    nameEn: 'Triceps Dips',
    targetMuscle: 'triceps',
    synergistMuscles: ['peito', 'ombros'],
    movementPattern: 'vertical_push',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Tronco ereto e cotovelos colados ao corpo para maximizar sobrecarga nos tríceps.',
  },
  {
    id: 'close_grip_bench_press',
    name: 'Supino com Pegada Fechada',
    nameEn: 'Close-Grip Bench Press',
    targetMuscle: 'triceps',
    synergistMuscles: ['peito', 'ombros'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Pegada na largura dos ombros (não feche demais para não estressar os punhos).',
  },
  {
    id: 'skull_crusher_ez_bar',
    name: 'Tríceps Testa com Barra W (Skull Crusher)',
    nameEn: 'EZ-Bar Skull Crusher',
    targetMuscle: 'triceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Desça a barra em direção à testa ou ligeiramente atrás da cabeça para manter tensão na cabeça longa.',
  },
  {
    id: 'skull_crusher_dumbbells',
    name: 'Tríceps Testa com Halteres',
    nameEn: 'Dumbbell Skull Crusher',
    targetMuscle: 'triceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 75,
    instructions: 'Pegada neutra descendo os halteres ao lado das orelhas.',
  },
  {
    id: 'cable_triceps_pushdown_rope',
    name: 'Tríceps Corda na Polia Alta',
    nameEn: 'Rope Cable Triceps Pushdown',
    targetMuscle: 'triceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Cotovelos fixos. Estenda até o final e abra a corda no ponto mais baixo.',
  },
  {
    id: 'cable_triceps_pushdown_straight_bar',
    name: 'Tríceps Pulley com Barra Reta',
    nameEn: 'Straight Bar Cable Pushdown',
    targetMuscle: 'triceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Permite maior sobrecarga para a cabeça lateral e medial do tríceps.',
  },
  {
    id: 'overhead_cable_triceps_extension_rope',
    name: 'Tríceps Francês na Polia com Corda',
    nameEn: 'Overhead Cable Triceps Extension',
    targetMuscle: 'triceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Cabo ajustado na altura média ou alta. Estenda os braços acima da cabeça mantendo os cotovelos altos.',
  },
  {
    id: 'overhead_dumbbell_triceps_extension_seated',
    name: 'Tríceps Francês com Halter Sentado (Bilateral)',
    nameEn: 'Seated Overhead Dumbbell Extension',
    targetMuscle: 'triceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 75,
    instructions: 'Segure um halter pesado com as duas mãos em formato de concha atrás da nuca.',
  },
  {
    id: 'triceps_kickback_dumbbell',
    name: 'Tríceps Coice com Halter',
    nameEn: 'Dumbbell Triceps Kickback',
    targetMuscle: 'triceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Tronco curvado, braço paralelo ao chão. Estenda o antebraço até travar o cotovelo.',
  },
  {
    id: 'bench_dips',
    name: 'Tríceps no Banco (Bench Dips)',
    nameEn: 'Bench Dips',
    targetMuscle: 'triceps',
    synergistMuscles: ['peito', 'ombros'],
    movementPattern: 'vertical_push',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Mãos apoiadas na borda do banco, descendo o quadril rente ao apoio.',
  },

  // ==========================================
  // PANTURRILHAS (CALVES)
  // ==========================================
  {
    id: 'standing_calf_raise_machine',
    name: 'Gêmeos em Pé na Máquina (Panturrilha)',
    nameEn: 'Standing Calf Raise Machine',
    targetMuscle: 'panturrilhas',
    synergistMuscles: [],
    movementPattern: 'calf_raise',
    mechanic: 'isolation',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Joelhos estendidos para focar no gastrocnêmio. Desça alongando ao máximo o calcanhar.',
  },
  {
    id: 'seated_calf_raise_machine',
    name: 'Gêmeos Sentado na Máquina (Panturrilha)',
    nameEn: 'Seated Calf Raise Machine',
    targetMuscle: 'panturrilhas',
    synergistMuscles: [],
    movementPattern: 'calf_raise',
    mechanic: 'isolation',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Joelhos flexionados a 90º. Foco primário no músculo sóleo profundo.',
  },
  {
    id: 'leg_press_calf_raise',
    name: 'Panturrilha no Leg Press 45º',
    nameEn: 'Leg Press Calf Raise',
    targetMuscle: 'panturrilhas',
    synergistMuscles: [],
    movementPattern: 'calf_raise',
    mechanic: 'isolation',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Pontas dos pés na borda inferior da plataforma com travas de segurança ativas.',
  },
  {
    id: 'single_leg_standing_calf_raise',
    name: 'Panturrilha Unilateral em Pé com Halter',
    nameEn: 'Single-Leg Standing Calf Raise',
    targetMuscle: 'panturrilhas',
    synergistMuscles: [],
    movementPattern: 'calf_raise',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 45,
    instructions: 'Equilibre-se em um degrau segurando um halter do mesmo lado da perna em apoio.',
  },

  // ==========================================
  // ABDÔMEN & CORE (ABS & CORE)
  // ==========================================
  {
    id: 'ab_wheel_rollout',
    name: 'Roda Abdominal (Ab Wheel Rollout)',
    nameEn: 'Ab Wheel Rollout',
    targetMuscle: 'abdomen',
    synergistMuscles: ['costas', 'ombros', 'peito'],
    movementPattern: 'core_anti_extension',
    mechanic: 'compound',
    equipment: 'other',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Ajoelhado, role a roda para frente mantendo a pelve retrovertida e o abdômen em tensão máxima.',
  },
  {
    id: 'hanging_leg_raise',
    name: 'Elevação de Pernas Suspenso na Barra',
    nameEn: 'Hanging Leg Raise',
    targetMuscle: 'abdomen',
    synergistMuscles: ['antibraco'],
    movementPattern: 'isolation',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 75,
    instructions: 'Pendurado na barra, erga as pernas retas ou joelhos até a altura do peito sem balançar.',
  },
  {
    id: 'cable_woodchopper_high_to_low',
    name: 'Woodchopper na Polia (Rotação Diagonal)',
    nameEn: 'Cable Woodchopper',
    targetMuscle: 'abdomen',
    synergistMuscles: ['ombros'],
    movementPattern: 'core_rotation',
    mechanic: 'compound',
    equipment: 'cable',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 60,
    instructions: 'Cruze o tronco em rotação controlada de cima para baixo ativando os oblíquos.',
  },
  {
    id: 'cable_crunch',
    name: 'Abdominal na Polia Alta Ajoelhado (Cable Crunch)',
    nameEn: 'Kneeling Cable Crunch',
    targetMuscle: 'abdomen',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Ajoelhado segurando a corda na nuca, flexione a coluna enrolando a caixa torácica em direção à pelve.',
  },
  {
    id: 'pallof_press_cable',
    name: 'Pallof Press na Polia (Anti-Rotação)',
    nameEn: 'Cable Pallof Press',
    targetMuscle: 'abdomen',
    synergistMuscles: ['gluteos'],
    movementPattern: 'core_anti_extension',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 60,
    instructions: 'Posicione-se lateralmente à polia. Estenda os braços à frente resistindo à rotação do tronco.',
  },
  {
    id: 'front_plank_weighted',
    name: 'Prancha Frontal com Sobrecarga',
    nameEn: 'Weighted Plank',
    targetMuscle: 'abdomen',
    synergistMuscles: ['gluteos', 'ombros'],
    movementPattern: 'core_anti_extension',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Prancha isométrica reta com anilha posicionada sobre a coluna torácica.',
  },

  // ==========================================
  // TRAPÉZIO (TRAPS)
  // ==========================================
  {
    id: 'barbell_shrug_standing',
    name: 'Encolhimento com Barra pela Frente',
    nameEn: 'Barbell Shrug',
    targetMuscle: 'trapezio',
    synergistMuscles: ['antibraco'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'barbell',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 90,
    instructions: 'Eleve os ombros verticalmente em direção às orelhas sem rodar as articulações.',
  },
  {
    id: 'dumbbell_shrug_standing',
    name: 'Encolhimento com Halteres em Pé',
    nameEn: 'Dumbbell Shrug',
    targetMuscle: 'trapezio',
    synergistMuscles: ['antibraco'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 75,
    instructions: 'Pegada neutra com os halteres na lateral do corpo permitindo elevação pura.',
  },
  {
    id: 'smith_machine_behind_back_shrug',
    name: 'Encolhimento no Smith por Trás (Lee Haney Shrug)',
    nameEn: 'Behind-the-Back Smith Machine Shrug',
    targetMuscle: 'trapezio',
    synergistMuscles: ['antibraco'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'smith',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 75,
    instructions: 'Barra posicionada logo abaixo dos glúteos puxando para cima.',
  },

  // --- Adicionais Peito ---
  {
    id: 'neutral_grip_dumbbell_press',
    name: 'Supino com Halteres Pegada Neutra',
    nameEn: 'Neutral Grip Dumbbell Bench Press',
    targetMuscle: 'peito',
    synergistMuscles: ['triceps', 'ombros'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Palmas voltadas uma para a outra, preservando o manguito rotador.',
  },
  {
    id: 'svend_press',
    name: 'Svend Press com Anilha',
    nameEn: 'Svend Press',
    targetMuscle: 'peito',
    synergistMuscles: ['ombros'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'other',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 45,
    instructions: 'Comprima duas anilhas entre as palmas das mãos empurrando para a frente.',
  },
  {
    id: 'guillotine_press',
    name: 'Supino Guilhotina com Barra',
    nameEn: 'Guillotine Bench Press',
    targetMuscle: 'peito',
    synergistMuscles: ['ombros'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Pegada aberta descendo a barra controladamente em direção ao pescoço superior.',
  },
  {
    id: 'incline_cable_fly',
    name: 'Crucifixo no Cabo em Banco Inclinado',
    nameEn: 'Incline Cable Fly',
    targetMuscle: 'peito',
    synergistMuscles: ['ombros'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 60,
    instructions: 'Banco a 30º entre as polias baixas, trazendo os cabos em arco ascendente.',
  },
  {
    id: 'decline_pushup',
    name: 'Flexão de Braço Declinada (Pés Elevados)',
    nameEn: 'Decline Push-Up',
    targetMuscle: 'peito',
    synergistMuscles: ['triceps', 'ombros'],
    movementPattern: 'horizontal_push',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Pés apoiados no banco, aumentando a sobrecarga no peitoral superior.',
  },

  // --- Adicionais Costas ---
  {
    id: 'neutral_grip_cable_row',
    name: 'Remada Baixa com Barra Pegada Neutra',
    nameEn: 'Neutral Grip Seated Cable Row',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'trapezio'],
    movementPattern: 'horizontal_pull',
    mechanic: 'compound',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Puxador neutro médio, focando na retração da escápula e latíssimo.',
  },
  {
    id: 'chest_supported_t_bar_row',
    name: 'Remada Cavalinho com Apoio no Peito',
    nameEn: 'Chest Supported T-Bar Row',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'trapezio'],
    movementPattern: 'horizontal_pull',
    mechanic: 'compound',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Peito travado na almofada, permitindo sobrecarga pesada sem estresse lombar.',
  },
  {
    id: 'single_arm_lat_pulldown',
    name: 'Puxada Alta Unilateral no Cabo',
    nameEn: 'Single Arm Lat Pulldown',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps'],
    movementPattern: 'vertical_pull',
    mechanic: 'compound',
    equipment: 'cable',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 60,
    instructions: 'Puxe o cotovelo para baixo e para dentro em direção ao quadril.',
  },
  {
    id: 'single_arm_machine_row',
    name: 'Remada Unilateral na Máquina Articulada',
    nameEn: 'Single Arm Machine Row',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps'],
    movementPattern: 'horizontal_pull',
    mechanic: 'compound',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Permite rotação sutil do tronco e foco absoluto no grande dorsal unilateral.',
  },
  {
    id: 'wide_grip_upright_row',
    name: 'Remada Alta com Barra (Pegada Aberta)',
    nameEn: 'Wide Grip Barbell Upright Row',
    targetMuscle: 'trapezio',
    synergistMuscles: ['ombros'],
    movementPattern: 'vertical_pull',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 75,
    instructions: 'Pegada aberta (mais larga que os ombros) para recrutar deltóides laterais e trapézio com segurança.',
  },
  {
    id: 'cable_upright_row',
    name: 'Remada Alta na Polia Baixa',
    nameEn: 'Cable Upright Row',
    targetMuscle: 'trapezio',
    synergistMuscles: ['ombros'],
    movementPattern: 'vertical_pull',
    mechanic: 'compound',
    equipment: 'cable',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 60,
    instructions: 'Puxe a barra reta ou corda até a altura do esterno superior.',
  },
  {
    id: 'weighted_pull_up',
    name: 'Barra Fixa com Peso Adicional (Cinto)',
    nameEn: 'Weighted Pull-Up',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'trapezio', 'antibraco'],
    movementPattern: 'vertical_pull',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 150,
    instructions: 'Cinto de imersão com anilhas para treino de força máxima na puxada vertical.',
  },
  {
    id: 'seal_row_barbell',
    name: 'Remada Seal com Barra (Banco Elevado)',
    nameEn: 'Barbell Seal Row',
    targetMuscle: 'costas',
    synergistMuscles: ['biceps', 'trapezio'],
    movementPattern: 'horizontal_pull',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 100,
    instructions: 'Deitado de bruços no banco plano elevado. Puxada horizontal pura com zero roubo.',
  },

  // --- Adicionais Quadríceps ---
  {
    id: 'close_stance_smith_squat',
    name: 'Agachamento no Smith com Pés Juntos',
    nameEn: 'Close-Stance Smith Squat',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'smith',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Pés juntos e ligeiramente à frente para recrutar o vasto lateral e reto femoral.',
  },
  {
    id: 'barbell_sumo_squat',
    name: 'Agachamento Sumô com Barra',
    nameEn: 'Barbell Sumo Squat',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos', 'isquiotibiais'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 120,
    instructions: 'Base larga com pontas apontando para fora, recrutando adutores e quadríceps.',
  },
  {
    id: 'double_dumbbell_front_squat',
    name: 'Agachamento Frontal com Dois Halteres',
    nameEn: 'Dumbbell Front Squat',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos', 'abdomen'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Halteres apoiados nos ombros, mantendo o tronco ereto e estável.',
  },
  {
    id: 'pistol_squat',
    name: 'Agachamento Pistola Unilateral (Pistol Squat)',
    nameEn: 'Pistol Squat',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos', 'abdomen', 'panturrilhas'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Agache sobre uma perna estendendo a outra à frente.',
  },
  {
    id: 'reverse_lunge_dumbbells',
    name: 'Afundo Reverso com Halteres',
    nameEn: 'Dumbbell Reverse Lunge',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos', 'isquiotibiais'],
    movementPattern: 'lunge',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 75,
    instructions: 'Dê o passo para trás para reduzir o estresse de cisalhamento patelar.',
  },
  {
    id: 'barbell_walking_lunge',
    name: 'Avanço com Barra nas Costas',
    nameEn: 'Barbell Walking Lunge',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos', 'isquiotibiais'],
    movementPattern: 'lunge',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 120,
    instructions: 'Passadas contínuas com a barra equilibrada sobre o trapézio.',
  },
  {
    id: 'single_leg_45_leg_press',
    name: 'Leg Press 45º Unilateral',
    nameEn: 'Single-Leg 45-Degree Leg Press',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Um pé na plataforma, controlando a descida profunda sem rotação do quadril.',
  },
  {
    id: 'horizontal_leg_press',
    name: 'Leg Press Horizontal',
    nameEn: 'Horizontal Leg Press Machine',
    targetMuscle: 'quadriceps',
    synergistMuscles: ['gluteos'],
    movementPattern: 'squat',
    mechanic: 'compound',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Empurrada horizontal guiada por cabo ou placas de peso.',
  },

  // --- Adicionais Isquiotibiais ---
  {
    id: 'single_leg_dumbbell_deadlift',
    name: 'Stiff Unilateral com Halter',
    nameEn: 'Single-Leg Dumbbell Romanian Deadlift',
    targetMuscle: 'isquiotibiais',
    synergistMuscles: ['gluteos'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Equilíbrio sobre uma perna estendendo a perna oposta para trás em linha reta.',
  },
  {
    id: 'smith_machine_rdl',
    name: 'Levantamento Terra Romeno no Smith',
    nameEn: 'Smith Machine Romanian Deadlift',
    targetMuscle: 'isquiotibiais',
    synergistMuscles: ['gluteos', 'lombar'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'smith',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Trajetória guiada que permite foco exclusivo na extensão do quadril.',
  },
  {
    id: 'single_leg_lying_curl',
    name: 'Mesa Flexora Unilateral',
    nameEn: 'Single Leg Lying Leg Curl',
    targetMuscle: 'isquiotibiais',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Permite igualar a força de flexão de joelho entre os dois membros.',
  },
  {
    id: 'swiss_ball_hamstring_curl',
    name: 'Flexão de Pernas na Bola Suíça',
    nameEn: 'Swiss Ball Hamstring Curl',
    targetMuscle: 'isquiotibiais',
    synergistMuscles: ['gluteos', 'abdomen'],
    movementPattern: 'isolation',
    mechanic: 'compound',
    equipment: 'other',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Deitado no chão, calcanhares na bola, eleve o quadril e puxe a bola para você.',
  },
  {
    id: 'smith_good_morning',
    name: 'Bom Dia no Smith (Good Morning)',
    nameEn: 'Smith Machine Good Morning',
    targetMuscle: 'isquiotibiais',
    synergistMuscles: ['gluteos', 'lombar'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'smith',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Incline o quadril mantendo a barra fixa sobre o trapézio.',
  },

  // --- Adicionais Glúteos ---
  {
    id: 'single_leg_hip_thrust_dumbbell',
    name: 'Elevação Pélvica Unilateral com Halter',
    nameEn: 'Single-Leg Hip Thrust',
    targetMuscle: 'gluteos',
    synergistMuscles: ['isquiotibiais'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Uma perna no chão e a outra erguida com halter apoiado no quadril.',
  },
  {
    id: 'frog_pump_weighted',
    name: 'Frog Pump com Anilha',
    nameEn: 'Weighted Frog Pump',
    targetMuscle: 'gluteos',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'other',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 45,
    instructions: 'Solas dos pés juntas em posição de borboleta, elevando o quadril em alta repetição.',
  },
  {
    id: 'band_monster_walk',
    name: 'Passada Lateral com Mini Band (Monster Walk)',
    nameEn: 'Banded Monster Walk',
    targetMuscle: 'gluteos',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'other',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 45,
    instructions: 'Elástico acima dos joelhos, caminhando lateralmente em posição de meio agachamento.',
  },
  {
    id: 'glute_focused_bulgarian_split_squat',
    name: 'Agachamento Búlgaro com Foco em Glúteos',
    nameEn: 'Glute-Biased Bulgarian Split Squat',
    targetMuscle: 'gluteos',
    synergistMuscles: ['quadriceps', 'isquiotibiais'],
    movementPattern: 'lunge',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Tronco inclinado para a frente a 45º e tíbia dianteira mais vertical.',
  },
  {
    id: 'barbell_glute_bridge',
    name: 'Ponte de Glúteos no Solo com Barra',
    nameEn: 'Barbell Glute Bridge',
    targetMuscle: 'gluteos',
    synergistMuscles: ['isquiotibiais'],
    movementPattern: 'hinge',
    mechanic: 'compound',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Deitado no chão, estendendo os quadris para cima contraindo os glúteos.',
  },

  // --- Adicionais Ombros ---
  {
    id: 'incline_bench_cable_lateral_raise',
    name: 'Elevação Lateral no Cabo Banco Inclinado',
    nameEn: 'Incline Bench Cable Lateral Raise',
    targetMuscle: 'ombros',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 60,
    instructions: 'Deitado de lado no banco inclinado a 45-60º para tensão máxima na posição encurtada.',
  },
  {
    id: 'plate_front_raise',
    name: 'Elevação Frontal com Anilha',
    nameEn: 'Weight Plate Front Raise',
    targetMuscle: 'ombros',
    synergistMuscles: ['peito'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'other',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Segure a anilha nas posições de 9 e 3 horas do relógio e eleve acima dos olhos.',
  },
  {
    id: 'cable_rear_delt_cross',
    name: 'Crucifixo Inverso no Cabo Cruzado',
    nameEn: 'Rear Delt Cable Crossover',
    targetMuscle: 'ombros',
    synergistMuscles: ['trapezio'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 60,
    instructions: 'Cabos cruzados na altura da cabeça puxando para trás sem manoplas.',
  },
  {
    id: 'dumbbell_upright_row',
    name: 'Remada Alta com Halteres',
    nameEn: 'Dumbbell Upright Row',
    targetMuscle: 'ombros',
    synergistMuscles: ['trapezio'],
    movementPattern: 'vertical_pull',
    mechanic: 'compound',
    equipment: 'dumbbell',
    planeOfMotion: 'frontal',
    defaultRestSeconds: 60,
    instructions: 'Puxe os halteres pelos cotovelos permitindo rotação livre dos punhos.',
  },
  {
    id: 'seated_dumbbell_rear_delt_raise',
    name: 'Elevação Posterior com Halteres Sentado',
    nameEn: 'Seated Bent-Over Rear Delt Raise',
    targetMuscle: 'ombros',
    synergistMuscles: ['trapezio'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 60,
    instructions: 'Tronco deitado sobre as coxas, abrindo os halteres lateralmente.',
  },

  // --- Adicionais Bíceps & Antebraço ---
  {
    id: 'twenty_one_bicep_curls',
    name: 'Rosca 21 com Barra W',
    nameEn: '21s Bicep Curl with EZ-Bar',
    targetMuscle: 'biceps',
    synergistMuscles: ['antibraco'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: '7 reps na metade inferior, 7 reps na metade superior e 7 reps na amplitude completa.',
  },
  {
    id: 'drag_curl_barbell',
    name: 'Rosca Drag com Barra (Drag Curl)',
    nameEn: 'Barbell Drag Curl',
    targetMuscle: 'biceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Puxe a barra arrastando-a rente ao abdômen e tórax jogando os cotovelos para trás.',
  },
  {
    id: 'cable_concentration_curl',
    name: 'Rosca Concentrada na Polia',
    nameEn: 'Standing Cable Concentration Curl',
    targetMuscle: 'biceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Puxada unilateral contínua mantendo o cotovelo isolado no espaço.',
  },
  {
    id: 'scott_hammer_curl',
    name: 'Rosca Martelo no Banco Scott',
    nameEn: 'Preacher Hammer Curl with Dumbbell',
    targetMuscle: 'biceps',
    synergistMuscles: ['antibraco'],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Isolamento estrito do braquial e cabeça curta com pegada neutra.',
  },
  {
    id: 'reverse_wrist_curl',
    name: 'Extensão de Punho com Barra (Antebraço Inverso)',
    nameEn: 'Reverse Wrist Curl with Barbell',
    targetMuscle: 'antibraco',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 45,
    instructions: 'Palmas voltadas para baixo, estendendo os punhos para cima.',
  },

  // --- Adicionais Tríceps ---
  {
    id: 'lying_french_press_ez_bar',
    name: 'Tríceps Francês Deitado com Barra W',
    nameEn: 'Lying French Press with EZ-Bar',
    targetMuscle: 'triceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 75,
    instructions: 'Braços inclinados a 45º para trás, descendo a barra atrás da cabeça.',
  },
  {
    id: 'incline_skull_crusher',
    name: 'Tríceps Testa no Banco Inclinado',
    nameEn: 'Incline Skull Crusher',
    targetMuscle: 'triceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'barbell',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 75,
    instructions: 'Banco a 30º, aumentando o alongamento passivo da cabeça longa do tríceps.',
  },
  {
    id: 'single_arm_cable_triceps_pushdown',
    name: 'Tríceps Unilateral na Polia com Manopla',
    nameEn: 'Single-Arm Cable Triceps Pushdown',
    targetMuscle: 'triceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'cable',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Foco no alinhamento articular perfeito para correção de desequilíbrios.',
  },
  {
    id: 'seated_dip_machine',
    name: 'Máquina de Tríceps Mergulho Sentado',
    nameEn: 'Seated Dip Machine',
    targetMuscle: 'triceps',
    synergistMuscles: ['peito', 'ombros'],
    movementPattern: 'vertical_push',
    mechanic: 'compound',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 90,
    instructions: 'Empurre as manoplas para baixo estendendo os cotovelos sem tirar o tronco do apoio.',
  },
  {
    id: 'tate_press_dumbbells',
    name: 'Tate Press com Halteres',
    nameEn: 'Tate Press with Dumbbells',
    targetMuscle: 'triceps',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 75,
    instructions: 'Halteres apontados para dentro tocando o peito, estendendo para fora e para cima.',
  },

  // --- Adicionais Panturrilhas ---
  {
    id: 'smith_machine_calf_raise_block',
    name: 'Gêmeos no Smith com Bloco',
    nameEn: 'Smith Machine Calf Raise on Block',
    targetMuscle: 'panturrilhas',
    synergistMuscles: [],
    movementPattern: 'calf_raise',
    mechanic: 'isolation',
    equipment: 'smith',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Pontas dos pés sobre o step, permitindo amplitude completa de dorsiflexão e flexão plantar.',
  },
  {
    id: 'donkey_calf_raise',
    name: 'Panturrilha Burrinho (Donkey Calf Raise)',
    nameEn: 'Donkey Calf Raise',
    targetMuscle: 'panturrilhas',
    synergistMuscles: [],
    movementPattern: 'calf_raise',
    mechanic: 'isolation',
    equipment: 'machine',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Tronco curvado para frente a 90º, alongando ao máximo o gastrocnêmio.',
  },

  // --- Adicionais Abdômen & Core ---
  {
    id: 'captains_chair_leg_raise',
    name: 'Elevação de Pernas na Torre / Paralela',
    nameEn: "Captain's Chair Leg Raise",
    targetMuscle: 'abdomen',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Costas apoiadas na almofada, elevando as pernas ou joelhos em direção ao peito.',
  },
  {
    id: 'bicycle_crunches',
    name: 'Abdominal Bicicleta',
    nameEn: 'Bicycle Crunches',
    targetMuscle: 'abdomen',
    synergistMuscles: [],
    movementPattern: 'core_rotation',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 45,
    instructions: 'Toque o cotovelo oposto no joelho que flexiona em rotação rítmica.',
  },
  {
    id: 'weighted_russian_twist',
    name: 'Russian Twist com Anilha',
    nameEn: 'Weighted Russian Twist',
    targetMuscle: 'abdomen',
    synergistMuscles: [],
    movementPattern: 'core_rotation',
    mechanic: 'compound',
    equipment: 'other',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 60,
    instructions: 'Pés elevados do chão, girando a anilha de um lado para o outro.',
  },
  {
    id: 'v_up_abdominals',
    name: 'Abdominal Canivete no Solo (V-Up)',
    nameEn: 'V-Up Abdominals',
    targetMuscle: 'abdomen',
    synergistMuscles: [],
    movementPattern: 'isolation',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Eleve o tronco e as pernas estendidas simultaneamente tocando as mãos nos pés.',
  },
  {
    id: 'stomach_vacuum',
    name: 'Stomach Vacuum (Vácuo Abdominal)',
    nameEn: 'Stomach Vacuum',
    targetMuscle: 'abdomen',
    synergistMuscles: [],
    movementPattern: 'core_anti_extension',
    mechanic: 'isolation',
    equipment: 'bodyweight',
    planeOfMotion: 'transverse',
    defaultRestSeconds: 45,
    instructions: 'Expire todo o ar dos pulmões e puxe o umbigo para dentro em direção à coluna.',
  },
  {
    id: 'rkc_plank',
    name: 'Prancha RKC de Alta Tensão',
    nameEn: 'RKC Plank',
    targetMuscle: 'abdomen',
    synergistMuscles: ['gluteos', 'ombros'],
    movementPattern: 'core_anti_extension',
    mechanic: 'compound',
    equipment: 'bodyweight',
    planeOfMotion: 'sagittal',
    defaultRestSeconds: 60,
    instructions: 'Prancha curta (15-30s) aplicando contração isométrica máxima de punhos, glúteos e abdômen.',
  },
];
